=== Smakovskyi/xml-json/src/main/resources/session.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="session">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="exams">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="exam" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element  name="hardLevel">
                                            <xs:simpleType>
                                                <xs:restriction  base="xs:byte">
                                                    <xs:minInclusive value="0"/>
                                                    <xs:maxInclusive value="50"/>
                                                </xs:restriction>

                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element  name="date">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern
                                                            value="\\d{2}\\.\\d{2}\\.\\d{2}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="name" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="credits">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="credit">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="date" maxOccurs="unbounded" minOccurs="0"/>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="name"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Smakovskyi/xml-json/src/main/resources/session.xml
<?xml version="1.0" encoding="UTF-8"?>
<session xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="session.xsd">
    <exams>
        <exam name="Software Testing">
            <hardLevel>50</hardLevel>
            <date>08.01.19</date>
        </exam>
        <exam name="Game dev">
            <hardLevel>20</hardLevel>
            <date>12.01.19</date>
        </exam>
    </exams>
    <credits>
        <credit name="parallel">
            <date>26.12.18</date>
            <date>19.01.19</date>
            <date>25.01.19</date>
        </credit>
    </credits>

</session>
